services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        MYSQL_CLIENT: mariadb-client
    image: sail-8.4/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mariadb
      - redis
      - postgres

  mariadb:
    image: 'mariadb:11'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: cfms_laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password123
    volumes:
      - 'sail-mariadb:/var/lib/mysql'
      - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      retries: 3
      timeout: 5s

  
   
 # mongodb:
  #  image: 'mongodb/mongodb-atlas-local:latest'
   # environment:
    #  - 'MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}'
     # - 'MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}'
   # volumes:
    #  - 'sail-mongodb:/data/db'
   # ports:
    #  - '${FORWARD_MONGODB_PORT:-27017}:27017'
   # networks:
    #  - sail
   # healthcheck:
    #  test:
     #   - CMD
      #  - mongosh
       # - 'mongodb://localhost:27017/admin'
       # - '--eval=db.runCommand({ping:1})'
     # retries: 3
     # timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - sail

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - sail

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cfms_pg
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5433:5432"
    volumes:
      - sail-postgres:/var/lib/postgresql/data
    networks:
      - sail

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"
    depends_on:
      - postgres
    networks:
      - sail
    volumes:
      - pgadmin-data:/var/lib/pgadmin   
  

networks:
  sail:
    driver: bridge

volumes:
  sail-mariadb:
    driver: local
  sail-redis:
    driver: local
  sail-postgres:
    driver: local
  pgadmin-data:   
    driver: local
